server:
  port: 8082
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clean_code
    username: postgres
    password: 1111111111
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
upload:
  folder: C:\java\Springboot\Springboot/upload/
